<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>92583fea-26a3-46a5-ab38-e8c982c4fd08</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../NotifyClassifier.Api/NotifyClassifier.Api.csproj" />
  </ItemGroup>

</Project>
