<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <RuntimeIdentifiers>android-arm;android-arm64;android-x64</RuntimeIdentifiers>
    <OutputType>Exe</OutputType>
    <RootNamespace>TennisWatch</RootNamespace>
    <UseMaui>true</UseMaui>
    <UseMonoRuntime>true</UseMonoRuntime>
    <UseDefaultPublishRuntimeIdentifier>false</UseDefaultPublishRuntimeIdentifier>
    <SingleProject>true</SingleProject>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <ApplicationTitle>Tennis</ApplicationTitle>
    <ApplicationId>dev.danielreis.tenniswatch</ApplicationId>
    <ApplicationDisplayVersion>0.1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <SupportedOSPlatformVersion>30.0</SupportedOSPlatformVersion>
    <RunAOTCompilation>false</RunAOTCompilation>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
  </PropertyGroup>
  <ItemGroup>
    <MauiImage Include="Resources/Images/*.svg" />
    <MauiIcon Include="Resources/AppIcon/appicon.png" Color="#000000" />
    <MauiSplashScreen Include="Resources/Splash/splash.svg" Color="#000000" BaseSize="64,64" />
    <PackageReference Include="Microsoft.Maui.Controls" />
    <ProjectReference Include="../TennisWatch.Core/TennisWatch.Core.csproj" />
  </ItemGroup>
</Project>
